(define (problem zeno-0) (:domain zeno-travel)
(:customization
(= :time-format "%d/%m/%Y %H:%M:%S")
(= :time-horizon-relative 2500)
(= :time-start "05/06/2007 08:00:00")
(= :time-unit :hours))

(:objects 
    p1 p2 p3 p4 p5 p6 p7 - person
    Barcelona Madrid Granada Sevilla Bilbao Almeria - city
    a1 a2 - aircraft
)
(:init
    (at p1 Granada) 
    (at p2 Bilbao)
    (at p3 Sevilla)
    (at p4 Granada)
    (at p5 Granada)
    (at p6 Granada)
    (at p7 Almeria)
    (at a1 Madrid)
    (at a2 Madrid)
    (= (fuel-limit) 15000000)
    (= (distance Granada Barcelona) 868)
    (= (distance Granada Bilbao) 829)
    (= (distance Granada Madrid) 421)
    (= (distance Granada Sevilla) 252)
    (= (distance Barcelona Granada) 868)
    (= (distance Barcelona Bilbao) 620)
    (= (distance Barcelona Madrid) 621)
    (= (distance Barcelona Sevilla) 1046)
    (= (distance Bilbao Granada) 829)
    (= (distance Bilbao Madrid) 395)
    (= (distance Bilbao Barcelona) 620)
    (= (distance Bilbao Sevilla) 933)
    (= (distance Madrid Granada) 421)
    (= (distance Madrid Bilbao) 395)
    (= (distance Madrid Barcelona) 621)
    (= (distance Madrid Sevilla) 534)
    (= (distance Sevilla Granada) 252)
    (= (distance Sevilla Bilbao) 933)
    (= (distance Sevilla Madrid) 534)
    (= (distance Sevilla Barcelona) 1046)
    (= (distance Almeria Barcelona) 809)
    (= (distance Almeria Granada) 162)
    (= (distance Almeria Bilbao) 958)
    (= (distance Almeria Madrid) 547)
    (= (distance Almeria Sevilla) 410)
    (= (distance Barcelona Almeria) 809)
    (= (distance Granada Almeria) 162)
    (= (distance Bilbao Almeria) 958)
    (= (distance Madrid Almeria) 547)
    (= (distance Sevilla Almeria) 410)
    (= (fuel a1) 4184)
    (= (fuel a2) 4184)
    (= (slow-speed a1) 10)
    (= (fast-speed a1) 20)
    (= (slow-speed a2) 10)
    (= (fast-speed a2) 20)
    (= (slow-burn a1) 1)
    (= (fast-burn a1) 2)
    (= (slow-burn a2) 1)
    (= (fast-burn a2) 2)
    (= (capacity a1) 4184)
    (= (capacity a2) 4184)
    (= (refuel-rate a1) 1)
    (= (refuel-rate a2) 1)
    (= (total-fuel-used) 0)
    (= (boarding-time) 1)
    (= (debarking-time) 1)
    (= (maxpasajeros a1) 2)
    (= (pasajeros a1) 0)
    (= (maxpasajeros a2) 2)
    (= (pasajeros a2) 0)
    (= (unpasajero) 1)
    (destino p1 Barcelona)
    (destino p2 Barcelona)
    (destino p3 Barcelona)
    (destino p4 Barcelona)
    (destino p5 Barcelona)
    (destino p6 Barcelona)
    (destino p7 Barcelona)
 )


(:tasks-goal
   :tasks(
   (transport-person p1 Barcelona)
   (transport-person p2 Barcelona)
   (transport-person p3 Barcelona)
   (transport-person p4 Barcelona)
   (transport-person p5 Barcelona)
   (transport-person p6 Barcelona)
   (transport-person p7 Barcelona)
   
   )
  )
)
   
    
    
    

    
