/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GIU;

import NapakalakiGame.Cultist;
import NapakalakiGame.CultistPlayer;
import NapakalakiGame.Player;

/**
 *
 * @author paco
 */
public class CultistView extends javax.swing.JPanel {
    
    
    private Cultist cultistModel;
    /**
     * Creates new form CultistView
     */
    public CultistView() {
        initComponents();
    }
    public Cultist getCultist()
    {
        return cultistModel;
    }
    
    public void setCultist(Player p)
    {
        if(p instanceof CultistPlayer) //para saber si es una instancia de esa clase
        {
            CultistPlayer cp = (CultistPlayer)p;
            this.setVisible(true);
            cultistModel = cp.getCultistCard();
            String nameText = cp.getName();
            name.setText(nameText);
            String levelText = Integer.toString(cultistModel.getBasicValue()) + " por cada sectario";
            level.setText(levelText);
            
            String siempreText = "Sectario para siempre";
            siempre.setText(siempreText);
            
        }
        else
        {
            this.setVisible(false);
        }
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        siempre = new javax.swing.JLabel();

        name.setText("Sectario");

        level.setText("+1 por cada sectario");

        siempre.setText("Sectario para siempre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addComponent(level)
                    .addComponent(siempre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(level)
                .addGap(18, 18, 18)
                .addComponent(siempre)
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel level;
    private javax.swing.JLabel name;
    private javax.swing.JLabel siempre;
    // End of variables declaration//GEN-END:variables
}
