/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GIU;

import NapakalakiGame.Treasure;
import NapakalakiGame.TreasureKind;
import java.awt.Color;

/**
 *
 * @author paco
 */
public class TreasureView extends javax.swing.JPanel {

    /**
     * Creates new form TreasureView
     */
    Treasure treasureModel;
    private boolean selected = false;
    public boolean isSelected()
    {
        return selected;
    }
    
    public Treasure getTreasure()
    {
        return treasureModel;
    }
    public TreasureView() {
        initComponents();
    }
    public void setTreasure (Treasure t) {
        treasureModel = t;
        Piezasdeoro.setText(Integer.toString(treasureModel.getGoldCoins()));
        Nombre.setText(treasureModel.getName());
        BonusMax.setText(Integer.toString(treasureModel.getMaxBonus()));
        BonusMin.setText(Integer.toString(treasureModel.getMinBonus()));
        Tipo.setText(treasureModel.getType().toString());
        // Se supone que el JLabel que se ha creado para mostrar el valor en
        // piezas de oro del tesoro se ha denominado coins
        // Proceder de manera similar con el resto de componentes
       // Finalizar con la siguiente orden para que los cambios se hagan
        //efectivos
        repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        BonusMax = new javax.swing.JLabel();
        BonusMin = new javax.swing.JLabel();
        Piezasdeoro = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        Nombre.setText("Nombre");

        BonusMax.setText("BonuxMax");

        BonusMin.setText("BonusMin");

        Piezasdeoro.setText("Piezas de Oro");

        Tipo.setText("Tipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BonusMax)
                        .addGap(18, 18, 18)
                        .addComponent(BonusMin, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Tipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Piezasdeoro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Nombre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BonusMax)
                    .addComponent(BonusMin, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Piezasdeoro)
                .addGap(18, 18, 18)
                .addComponent(Tipo))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
        if(selected == true)
        {
            selected = false;
           
            this.setBackground(Color.DARK_GRAY);
            setOpaque(false);
            
            
        }
        else
        {
            selected = true;
            this.setBackground(Color.magenta);
            setOpaque(true);
        }
        
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BonusMax;
    private javax.swing.JLabel BonusMin;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Piezasdeoro;
    private javax.swing.JLabel Tipo;
    // End of variables declaration//GEN-END:variables
}
